import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { prisma } from '../prisma/client';
import { logger } from '../lib/logger';

const REPORTS_DIR = path.join(process.cwd(), 'reports');

export const ensureReportsDir = async () => {
  try {
    await fs.promises.access(REPORTS_DIR);
  } catch {
    await fs.promises.mkdir(REPORTS_DIR, { recursive: true });
  }
};

export const generatePDFReport = async (teacherId: string, studentId: string, summary: string): Promise<string> => {
  await ensureReportsDir();

  // Step 1: Gather data inside transaction (DB reads only)
  const [student, grades, recordings] = await prisma.$transaction(async (tx) => {
    return Promise.all([
      tx.user.findUnique({ where: { id: studentId }, select: { firstName: true, lastName: true, email: true } }),
      tx.grade.findMany({
        where: { studentId },
        select: { subject: true, grade: true, type: true, notes: true, createdAt: true },
      }),
      tx.recording.count({ where: { studentId } }),
    ]);
  });

  if (!student) throw new Error('Student not found');

  const fileName = `report-${studentId}-${Date.now()}.pdf`;
  const docPath = path.join(REPORTS_DIR, fileName);

  // Step 2: Generate PDF OUTSIDE the DB transaction
  // If this fails, no DB record is orphaned. If DB insert later fails, we clean up the file.
  const pdfUrl = await new Promise<string>((resolve, reject) => {
    const doc = new PDFDocument({ autoFirstPage: true });
    const stream = fs.createWriteStream(docPath);
    doc.pipe(stream);

    // Header (Arabic)
    doc.fontSize(24).text('التعليم الإلكتروني', { align: 'center' }).moveDown(0.5);
    doc.fontSize(16).text('تقرير تقدم الطالب / Student Report', { align: 'center' }).moveDown();
    doc.fontSize(12).text('======================================================', { align: 'center' }).moveDown(0.5);

    // Student Info
    doc.fontSize(14).text(`${student.firstName} ${student.lastName}`, { underline: true }).moveDown();
    doc.fontSize(10).text(`Email: ${student.email}`).moveDown();
    doc.text(`تاريخ التقرير / Report Date: ${new Date().toLocaleDateString('ar-SA')}`).moveDown(1);

    // Grades section
    doc.fontSize(14).text('الدرجات / Grades', { underline: true }).moveDown(0.5);
    if (grades.length === 0) {
      doc.fontSize(10).text('لا توجد درجات مسجلة بعد / No grades recorded yet').moveDown();
    } else {
      grades.forEach((g) => {
        const typeLabel = gradeTypeArabic(g.type);
        doc
          .fontSize(10)
          .text(`- ${g.subject}: ${g.grade} (${typeLabel})${g.notes ? ` — ${g.notes}` : ''}`)
          .moveDown(0.3);
      });
    }

    // Recordings count
    doc.moveDown().fontSize(12).text(`التسجيلات / Recordings: ${recordings}`).moveDown(1);

    // Summary
    doc.fontSize(14).text('الملخص / Summary:', { underline: true }).moveDown();
    doc
      .fontSize(10)
      .text(summary || 'لا يوجد ملخص / No summary provided')
      .moveDown(1);

    // Footer
    const footerY = doc.page.height - doc.page.margins.bottom - 20;
    doc
      .fontSize(8)
      .text('======================================================', doc.page.margins.left, footerY, {
        align: 'center',
        width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
      });
    doc.text(`Generated by: ${teacherId} | ${new Date().toISOString()}`, { align: 'center' });

    doc.end();
    stream.on('finish', () => resolve(`/reports/${fileName}`));
    stream.on('error', (err) => {
      logger.error({ err }, 'PDF generation failed');
      reject(err);
    });
  });

  return pdfUrl;
};

function gradeTypeArabic(t: string): string {
  const map: Record<string, string> = {
    QUIZ: 'اختبار قصير',
    ASSIGNMENT: 'واجب',
    EXAM: 'امتحان',
    ORAL: 'شفوي',
    PARTICIPATION: 'مشاركة',
  };
  return map[t] || t;
}
