import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { prisma } from '../prisma/client';
import { logger } from '../lib/logger';

const REPORTS_DIR = path.join(process.cwd(), 'reports');

export const ensureReportsDir = async () => {
  try {
    await fs.promises.access(REPORTS_DIR);
  } catch {
    await fs.promises.mkdir(REPORTS_DIR, { recursive: true });
  }
};

export const generatePDFReport = async (teacherId: string, studentId: string, summary: string): Promise<string> => {
  await ensureReportsDir();

  // Step 1: Gather data inside transaction (DB reads only)
  const [student, grades, recordings] = await prisma.$transaction(async (tx) => {
    return Promise.all([
      tx.user.findUnique({ where: { id: studentId }, select: { firstName: true, lastName: true, email: true } }),
      tx.grade.findMany({
        where: { studentId, teacherId },
        select: {
          grade: true,
          type: true,
          notes: true,
          createdAt: true,
          surah: { select: { nameAr: true, nameEn: true } },
        },
      }),
      tx.recording.count({ where: { studentId } }),
    ]);
  });

  if (!student) throw new Error('Student not found');

  const fileName = `report-${studentId}-${Date.now()}.pdf`;
  const docPath = path.join(REPORTS_DIR, fileName);

  // Step 2: Generate PDF OUTSIDE the DB transaction
  // If this fails, no DB record is orphaned. If DB insert later fails, we clean up the file.
  const pdfUrl = await new Promise<string>((resolve, reject) => {
    const doc = new PDFDocument({ autoFirstPage: true });
    const stream = fs.createWriteStream(docPath);
    doc.pipe(stream);

    // Header (Arabic) — Quran Review branding
    doc.fontSize(24).text('مراجعة القرآن', { align: 'center' }).moveDown(0.5);
    doc.fontSize(16).text('تقرير تقدم الطالب / Student Report', { align: 'center' }).moveDown();
    doc.fontSize(12).text('======================================================', { align: 'center' }).moveDown(0.5);

    // Student Info
    doc.fontSize(14).text(`${student.firstName} ${student.lastName}`, { underline: true }).moveDown();
    doc.fontSize(10).text(`Email: ${student.email}`).moveDown();
    doc.text(`تاريخ التقرير / Report Date: ${new Date().toLocaleDateString('ar-SA')}`).moveDown(1);

    // Grades section
    doc.fontSize(14).text('الدرجات / Grades', { underline: true }).moveDown(0.5);
    if (grades.length === 0) {
      doc.fontSize(10).text('لا توجد درجات مسجلة بعد / No grades recorded yet').moveDown();
    } else {
      grades.forEach((g) => {
        const typeLabel = gradeTypeArabic(g.type);
        const surahLabel = g.surah ? `${g.surah.nameAr} (${g.surah.nameEn})` : 'تلاوة عامة / Overall Recital';
        doc
          .fontSize(10)
          .text(`- ${surahLabel}: ${g.grade} (${typeLabel})${g.notes ? ` — ${g.notes}` : ''}`)
          .moveDown(0.3);
      });
    }

    // Recordings count
    doc.moveDown().fontSize(12).text(`التسجيلات / Recordings: ${recordings}`).moveDown(1);

    // Summary
    doc.fontSize(14).text('الملخص / Summary:', { underline: true }).moveDown();
    doc
      .fontSize(10)
      .text(summary || 'لا يوجد ملخص / No summary provided')
      .moveDown(1);

    // Footer
    const footerY = doc.page.height - doc.page.margins.bottom - 20;
    doc.fontSize(8).text('======================================================', doc.page.margins.left, footerY, {
      align: 'center',
      width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
    });
    doc.text(`Generated by: ${teacherId} | ${new Date().toISOString()}`, { align: 'center' });

    doc.end();
    stream.on('finish', () => resolve(`/reports/${fileName}`));
    stream.on('error', (err) => {
      logger.error({ err }, 'PDF generation failed');
      reject(err);
    });
  });

  return pdfUrl;
};

function gradeTypeArabic(t: string): string {
  const map: Record<string, string> = {
    QUIZ: 'اختبار قصير',
    ASSIGNMENT: 'واجب',
    EXAM: 'امتحان',
    ORAL: 'شفوي',
    PARTICIPATION: 'مشاركة',
  };
  return map[t] || t;
}

const CERTS_DIR = path.join(process.cwd(), 'certificates');

export const ensureCertsDir = async () => {
  try {
    await fs.promises.access(CERTS_DIR);
  } catch {
    await fs.promises.mkdir(CERTS_DIR, { recursive: true });
  }
};

export const generateCertificatePDF = async (studentId: string): Promise<string> => {
  await ensureCertsDir();

  const student = await prisma.user.findUnique({
    where: { id: studentId },
    select: { firstName: true, lastName: true, email: true },
  });
  if (!student) throw new Error('Student not found');

  const fileName = `certificate-${studentId}-${Date.now()}.pdf`;
  const docPath = path.join(CERTS_DIR, fileName);

  await new Promise<void>((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', layout: 'landscape', autoFirstPage: true });
    const stream = fs.createWriteStream(docPath);
    doc.pipe(stream);

    const { width, height } = doc.page;
    const margin = 40;

    // Decorative border
    doc.rect(margin, margin, width - 2 * margin, height - 2 * margin).stroke('#b8860b');
    doc.rect(margin + 8, margin + 8, width - 2 * (margin + 8), height - 2 * (margin + 8)).stroke('#b8860b');

    // Title
    doc.moveDown(2);
    doc.fontSize(32).fillColor('#1a1a2e').text('ختم القرآن الكريم', { align: 'center' }).moveDown(0.5);
    doc.fontSize(20).text('Certificate of Quran Completion', { align: 'center' }).moveDown(1.5);

    // Divider
    doc
      .moveTo(margin + 60, doc.y)
      .lineTo(width - margin - 60, doc.y)
      .stroke('#b8860b')
      .moveDown(1);

    // Body
    doc.fontSize(14).fillColor('#333').text('This certifies that', { align: 'center' }).moveDown(0.5);
    doc
      .fontSize(22)
      .fillColor('#1a1a2e')
      .text(`${student.firstName} ${student.lastName}`, { align: 'center', underline: true })
      .moveDown(0.5);
    doc
      .fontSize(14)
      .fillColor('#333')
      .text('has successfully memorized and reviewed all 114 Surahs of the Holy Quran', {
        align: 'center',
      })
      .moveDown(0.5);
    doc
      .fontSize(14)
      .text(`مَعَ تَمَّامِ الْحِفْظِ وَالْمُرَاجَعَةِ لِجَمِيعِ سُوَرِ الْقُرْآنِ الْكَرِيمِ`, { align: 'center' })
      .moveDown(1.5);

    // Date
    doc
      .fontSize(11)
      .fillColor('#666')
      .text(`Issued: ${new Date().toLocaleDateString('en-GB')}`, { align: 'center' });

    doc.end();
    stream.on('finish', resolve);
    stream.on('error', (err) => {
      logger.error({ err }, 'Certificate PDF generation failed');
      reject(err);
    });
  });

  return `/certificates/${fileName}`;
};
