import { ScrollViewStyleReset } from 'expo-router/html';
import type { PropsWithChildren } from 'react';

/**
 * Root HTML document for the **web export only** — it never ships in the
 * iOS/Android bundles and runs in Node during static rendering, so it must not
 * use client-side APIs or hooks.
 *
 * Expo's default shell emits no <title>, no description, no social-preview
 * tags and `lang="en"` on an Arabic-first, RTL app: every exported page had a
 * blank browser tab and produced an empty link preview when shared. Everything
 * below is the static, crawler-visible baseline; individual screens can still
 * override the title at runtime.
 */

const APP_NAME = 'مراجعة القرآن';
const APP_NAME_EN = 'Quran Review';
const DESCRIPTION =
  'منصة مراجعة القرآن: متابعة الحفظ والتلاوة بين الطالب والمعلم وولي الأمر. Quran memorization review and teacher-guided recitation tracking.';

/** '/' on a root domain, '/education-management/' on GitHub Pages. */
const BASE = (() => {
  const raw = (process.env.EXPO_BASE_URL ?? '').trim();
  if (!raw || raw === '/') return '/';
  return `/${raw.replace(/^\/+|\/+$/g, '')}/`;
})();

export default function Root({ children }: PropsWithChildren) {
  return (
    <html lang="ar" dir="rtl">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        <title>{`${APP_NAME} · ${APP_NAME_EN}`}</title>
        <meta name="description" content={DESCRIPTION} />
        <meta name="application-name" content={APP_NAME} />
        <meta name="theme-color" content="#1B5E20" />

        {/* Social previews — WhatsApp is the primary sharing channel here. */}
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content={APP_NAME} />
        <meta property="og:title" content={`${APP_NAME} · ${APP_NAME_EN}`} />
        <meta property="og:description" content={DESCRIPTION} />
        <meta property="og:locale" content="ar_AR" />
        <meta property="og:image" content={`${BASE}assets/assets/icon.png`} />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:title" content={`${APP_NAME} · ${APP_NAME_EN}`} />
        <meta name="twitter:description" content={DESCRIPTION} />

        {/* Installability: the manifest is generated by scripts/prepare-github-pages.js. */}
        <link rel="manifest" href={`${BASE}manifest.json`} />
        <link rel="apple-touch-icon" href={`${BASE}assets/assets/icon.png`} />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-title" content={APP_NAME} />
        <meta name="mobile-web-app-capable" content="yes" />

        {/*
          Disable body scrolling on web so ScrollView components work as they do
          on native. Remove this if a global web scrollbar is ever wanted.
        */}
        <ScrollViewStyleReset />

        {/* Background matches the app shell so there is no white flash before hydration. */}
        <style dangerouslySetInnerHTML={{ __html: BACKGROUND_STYLE }} />
      </head>
      <body>{children}</body>
    </html>
  );
}

const BACKGROUND_STYLE = `
body { background-color: #F5F5F3; }
@media (prefers-color-scheme: dark) {
  body { background-color: #121212; }
}
`;
